### ISSUE TITLE
TIAX Export not possible with newest ax2tia package

### ISSUE THREAD

**Issue by RauerJ** [simatic-ax/ae-tiax#20]
**Describe the bug**
The TIAX Export gives an error message when a newer version of ax2tia is used. It works fine with sdk 3.0.10 and ax2tia 4.2.10, but not after apax update to 3.0.12 and 4.4.16

**To Reproduce**
1. Open the project
2. Run apax update (all)
3. Run apax create-tialib

**Screenshots**
![image](https://user-images.githubusercontent.com/95907495/224307374-97144e1a-b7b5-4f3f-9aa0-20e0a73a503c.png)

**Comment by sjuergen** [comment]
@RauerJ thanks for the feedback. I'll have a look on it

**Comment by sjuergen** [comment]
This project can not be used with `@ax/ax2tia": 4.2.16`. Please use `@ax/ax2tia": 4.2.10`

I already addressed the issue.

**Comment by sjuergen** [comment]
should be solved with latest version of ax2tia. Could you pls confirm?

**Comment by sjuergen** [comment]
it works with SDK 2405.0.0

**Comment by sjuergen** [comment]
retested and it works now
