### ISSUE TITLE
Tests disabled because of errors

### ISSUE THREAD

**Issue by sjuergen** [simatic-ax/ae-tiax#36]
In the commit: https://github.com/simatic-ax/ae-tiax/commit/f2867541135e4fd5ebddc4d63abd4045bbb49790

Three tests are commented out. Because of errors from AxUnit --> repair the tests and enable them again.

Regards

**Comment by BeckerStS** [comment]
fixes in MR :
https://github.com/simatic-ax/ae-tiax/pull/38

**Comment by sjuergen** [comment]
have linked the PR to the issue
